# Generated by Django 2.2.1 on 2019-05-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(default='toyota', max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('transmission', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('horse_power', models.CharField(max_length=50)),
                ('propellant', models.CharField(max_length=100)),
                ('car_image', models.FileField(default='default.jpg', upload_to='car_image')),
            ],
        ),
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('manufacturer_logo', models.FileField(default='default.jpg', upload_to='manufacturer_logo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=100)),
                ('cars', models.ManyToManyField(to='car.Car')),
            ],
        ),
        migrations.CreateModel(
            name='ManufactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=50)),
                ('car_type', models.CharField(default='SUV', max_length=100)),
                ('manufactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Manufactor')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Manufactor'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.ManufactorModel'),
        ),
    ]
